### ISSUE TITLE
try-finally different than in the semantics

### ISSUE THREAD

**Issue by tilk** [brownplt/LambdaS5#50]
In the "A Tested Semantics" paper, the try-finally expression always gives the same outcome as its left subexpression if the finalizer does not fail - in particular, try v1 finally v2 results in v1. In the interpreter, this expression returns v2.

**Comment by justinpombrio** [comment]
This looks to me like a typo in the paper: the EFinallyPop rule should read:
    E < try v finally e > → E < e >
instead of what it actually says:
    E < try v finally e > → E < e; v >
As far as I can tell this would match both the semantics of JS and the behavior of the interpreter.

**Comment by tilk** [comment]
According to ES5, 12.14, semantics of try Block Finally, actually the behavior in the paper is the correct one: the standard says that if the finally block finishes normally, then the final result is the result of the try block.

**Comment by jpolitz** [comment]
There does seem to be a discrepancy with the spec.  Oddly, Chrome _and_ Firefox thinks the result is the result of finally (this is true in the Chrome console and in node v0.10.35):

```
> try { 3; } finally { 4; }
4
```

I don't see a test in https://github.com/tc39/test262/tree/master/test/language/statements/try that would tickle this behavior.  Most of those tests are just checking for the _effects_ that the block has, not the actual result.  And if a try/finally appears that way in a function body, it will have the implicit return undefined added, so it would be hard to notice without a test that does eval().

**Comment by lijunsong** [comment]
The interpreter returns the body value now.
